name:                chatterbots
version:             0.1.0.0
github:              "githubuser/chatterbots"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/chatterbots#readme>

dependencies:
- base >= 4.7 && < 5
- random

library:
  source-dirs: src

executables:
  chatterbots-exe:
    main:                Eliza.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chatterbots

tests:
  chatterbots-test:
    main:                ChatterbotTest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chatterbots
    - HUnit
